import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    'readme',
    'layers',
    {
      type: 'category',
      label: 'Conventions',
      collapsed: false,
      items: [
        'conventions/project-context-files',
        'conventions/runtime-guardrails',
        'conventions/prompt-assets',
        'conventions/agent-skills',
        'conventions/design-ui',
        'conventions/evaluation-testing',
        'conventions/discoverability',
        'conventions/protocols',
        'conventions/architecture-decisions',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'examples/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples/generated',
        },
      ],
    },
  ],
};

export default sidebars;
